Repository HXTIA/workboard_backend, pull requests merged in 2022-10, with the labels that each got.

#31 💥Feat/menu build
  src/main/java/run/hxtia/workbd/common/config/SwaggerCfg.java
  src/main/java/run/hxtia/workbd/common/mapstruct/MapStructs.java
  src/main/java/run/hxtia/workbd/common/util/Constants.java
  src/main/java/run/hxtia/workbd/controller/admin/AdminUserController.java
  src/main/java/run/hxtia/workbd/controller/admin/ResourcesController.java
  src/main/java/run/hxtia/workbd/mapper/ResourceMapper.java
  src/main/java/run/hxtia/workbd/pojo/dto/AdminUserInfoDto.java
  src/main/java/run/hxtia/workbd/pojo/dto/ResourceDto.java
  src/main/java/run/hxtia/workbd/pojo/po/AdminUsers.java
  src/main/java/run/hxtia/workbd/pojo/po/Resource.java
  src/main/java/run/hxtia/workbd/pojo/vo/response/AdminUserVo.java
  src/main/java/run/hxtia/workbd/service/admin/AdminUserRoleService.java
  src/main/java/run/hxtia/workbd/service/admin/AdminUserService.java
  src/main/java/run/hxtia/workbd/service/admin/ResourceService.java
  src/main/java/run/hxtia/workbd/service/admin/RoleResourceService.java
  src/main/java/run/hxtia/workbd/service/admin/RoleService.java
  src/main/java/run/hxtia/workbd/service/admin/impl/AdminUserRoleServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/AdminUserServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/ResourceServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/RoleResourceServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/RoleServiceImpl.java
  src/test/java/run/hxtia/workbd/test/service/UserRoleServiceTest.java
Labels: feature

#36 🚨 Feat/work
  src/main/java/run/hxtia/workbd/common/commoncontroller/BaseController.java
  src/main/java/run/hxtia/workbd/common/config/SwaggerCfg.java
  src/main/java/run/hxtia/workbd/common/enhance/MpLambdaQueryWrapper.java
  src/main/java/run/hxtia/workbd/common/mapstruct/MapStructs.java
  src/main/java/run/hxtia/workbd/common/shiro/ShiroConfig.java
  src/main/java/run/hxtia/workbd/common/upload/UploadEditParam.java
  src/main/java/run/hxtia/workbd/common/upload/Uploads.java
  src/main/java/run/hxtia/workbd/common/util/Constants.java
  src/main/java/run/hxtia/workbd/common/util/Streams.java
  src/main/java/run/hxtia/workbd/common/validator/ZOTNumber.java
  src/main/java/run/hxtia/workbd/controller/admin/WorkController.java
  src/main/java/run/hxtia/workbd/controller/miniapp/WxUserWorkController.java
  src/main/java/run/hxtia/workbd/controller/miniapp/WxWorkController.java
  src/main/java/run/hxtia/workbd/mapper/UserWorkMapper.java
  src/main/java/run/hxtia/workbd/mapper/WorkMapper.java
  src/main/java/run/hxtia/workbd/pojo/dto/WorkInfoDto.java
  src/main/java/run/hxtia/workbd/pojo/po/UserWork.java
  src/main/java/run/hxtia/workbd/pojo/po/Work.java
  src/main/java/run/hxtia/workbd/pojo/vo/request/page/WorkPageReqVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/request/page/base/WxWorkPageReqVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/request/save/UserWorkReqVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/request/save/WorkReqVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/request/save/WorkUploadReqVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/response/UserWorkVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/response/WorkVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/result/CodeMsg.java
  src/main/java/run/hxtia/workbd/service/admin/UserWorkService.java
  src/main/java/run/hxtia/workbd/service/admin/WorkService.java
  src/main/java/run/hxtia/workbd/service/admin/impl/AdminUserServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/OrganizationServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/ResourceServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/UserWorkServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/WorkServiceImpl.java
  src/main/java/run/hxtia/workbd/service/miniapp/WxUserWorkService.java
  src/main/java/run/hxtia/workbd/service/miniapp/WxWorkService.java
  src/main/java/run/hxtia/workbd/service/miniapp/impl/WxUserServiceImpl.java
  src/main/java/run/hxtia/workbd/service/miniapp/impl/WxUserWorkServiceImpl.java
  src/main/java/run/hxtia/workbd/service/miniapp/impl/WxWorkServiceImpl.java
  src/test/java/run/hxtia/workbd/test/common/FileTreePrintsTest.java
  src/test/java/run/hxtia/workbd/test/common/MapStructTest.java
  src/test/java/run/hxtia/workbd/test/service/WorkServiceTest.java
Labels: enhancement, feature

#38 Feat/user info get
  src/main/java/run/hxtia/workbd/common/mapstruct/MapStructs.java
  src/main/java/run/hxtia/workbd/pojo/vo/response/AdminUserVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/result/CodeMsg.java
  src/main/java/run/hxtia/workbd/service/admin/AdminUserService.java
  src/main/java/run/hxtia/workbd/service/admin/OrganizationService.java
  src/main/java/run/hxtia/workbd/service/admin/impl/AdminUserServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/OrganizationServiceImpl.java
Labels: feature

#37 🚀 Feat/permission
  src/main/java/run/hxtia/workbd/common/exception/CommonExceptionHandler.java
  src/main/java/run/hxtia/workbd/common/redis/Redises.java
  src/main/java/run/hxtia/workbd/common/shiro/TokenFilter.java
  src/main/java/run/hxtia/workbd/common/shiro/TokenRealm.java
  src/main/java/run/hxtia/workbd/common/util/Constants.java
  src/main/java/run/hxtia/workbd/common/util/Md5s.java
  src/main/java/run/hxtia/workbd/common/util/MiniApps.java
  src/main/java/run/hxtia/workbd/controller/admin/AdminUserController.java
  src/main/java/run/hxtia/workbd/controller/admin/OrganizationController.java
  src/main/java/run/hxtia/workbd/controller/admin/RoleController.java
  src/main/java/run/hxtia/workbd/controller/admin/WorkController.java
  src/main/java/run/hxtia/workbd/pojo/dto/AdminUserInfoDto.java
  src/main/java/run/hxtia/workbd/pojo/dto/AdminUserPermissionDto.java
  src/main/java/run/hxtia/workbd/pojo/vo/result/CodeMsg.java
  src/main/java/run/hxtia/workbd/service/admin/AdminUserRoleService.java
  src/main/java/run/hxtia/workbd/service/admin/AdminUserService.java
  src/main/java/run/hxtia/workbd/service/admin/ResourceService.java
  src/main/java/run/hxtia/workbd/service/admin/RoleService.java
  src/main/java/run/hxtia/workbd/service/admin/impl/AdminUserRoleServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/AdminUserServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/ResourceServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/RoleResourceServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/RoleServiceImpl.java
  src/main/java/run/hxtia/workbd/service/miniapp/impl/WxUserServiceImpl.java
  src/test/java/run/hxtia/workbd/test/service/UserRoleServiceTest.java
Labels: enhancement, feature

#49 feat: 💡添加图形验证码
  pom.xml
  src/main/java/run/hxtia/workbd/common/shiro/ShiroConfig.java
  src/main/java/run/hxtia/workbd/common/shiro/TokenFilter.java
  src/main/java/run/hxtia/workbd/common/util/Captchas.java
  src/main/java/run/hxtia/workbd/common/util/Constants.java
  src/main/java/run/hxtia/workbd/controller/admin/AdminUserController.java
  src/main/java/run/hxtia/workbd/pojo/vo/request/AdminLoginReqVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/request/CaptchaReqVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/request/save/AdminUserMemberPwdReqVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/request/save/AdminUserPasswordReqVo.java
  src/main/java/run/hxtia/workbd/pojo/vo/response/CaptchaVo.java
  src/main/java/run/hxtia/workbd/service/admin/impl/AdminUserServiceImpl.java
  src/main/java/run/hxtia/workbd/service/admin/impl/EmailServiceImpl.java
Labels: enhancement

#47 docs: 📝添加LICENSE
  LICENSE
Labels: documentation

#52 📝docs: 📝更新配置文件模板
  src/main/java/run/hxtia/workbd/common/prop/WorkBoardProperties.java
  src/main/resources/application-dev.yml.template
Labels: documentation

#51 🐛fix: #50 🐛修复无权限的问题
  src/main/java/run/hxtia/workbd/common/shiro/TokenRealm.java
Labels: bug
